/*
 Copyright 2023 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
export const CAPTION_LANGUAGES: {[key: string]: string} = {
  'af-za': 'Afrikaans',
  'az-az': 'Azərbaycanca',
  'id-id': 'Bahasa Indonesia',
  'ms-my': 'Bahasa Melayu',
  'jv-id': 'Basa Jawa',
  'su-id': 'Basa Sunda',
  'ca-es': 'Català',
  'da-dk': 'Dansk',
  'de-de': 'German',
  'en-au': 'English',
  'en-ca': 'English',
  'en-gh': 'English',
  'en-in': 'English',
  'en-ke': 'English',
  'en-nz': 'English',
  'en-ng': 'English',
  'en-ph': 'English',
  'en-za': 'English',
  'en-tz': 'English',
  'en-gb': 'English',
  'en-us': 'English',
  'es_es': 'Spanish',
  'es-ar': 'Spanish',
  'es-bo': 'Spanish',
  'es-cl': 'Spanish',
  'es-co': 'Spanish',
  'es-cr': 'Spanish',
  'es-ec': 'Spanish',
  'es-sv': 'Spanish',
  'es-es': 'Spanish',
  'es-us': 'Spanish',
  'es-gt': 'Spanish',
  'es-hn': 'Spanish',
  'es-mx': 'Spanish',
  'es-ni': 'Spanish',
  'es-pa': 'Spanish',
  'es-py': 'Spanish',
  'es-pe': 'Spanish',
  'es-pr': 'Spanish',
  'es-do': 'Spanish',
  'es-uy': 'Spanish',
  'es-ve': 'Spanish',
  'eu-es': 'Spanish',
  'fil-ph': 'Filipino',
  'fr-fr': 'French',
  'gl-es': 'Galego',
  'hr-hr': 'Hrvatski',
  'zu-za': 'IsiZulu',
  'it-it': 'Italiano',
  'it-ch': 'Italiano',
  'sw-ke': 'Kiswahili',
  'sw-tz': 'Kiswahili',
  'lv-lv': 'Latviešu',
  'lt-lt': 'Lietuvių',
  'hu-hu': 'Magyar',
  'nl-nl': 'Nederlands',
  'nb-no': 'Norsk bokmål',
  'pl-pl': 'Polski',
  'pt-br': 'Português',
  'pt-pt': 'Português',
  'ru-ru': 'Pусский',
  'ro-ro': 'Română',
  'sk-sk': 'Slovenčina',
  'sl-si': 'Slovenščina',
  'fi-fi': 'Suomi',
  'sv-se': 'Swedish',
  'vi-vn': 'Tiếng Việt',
  'tr-tr': 'Türkçe',
  'is-is': 'Íslenska',
  'cs-cz': 'Čeština',
  'el-gr': 'Ελληνικά',
  'sr-rs': 'Српски',
  'uk-ua': 'Українська',
  'bg-bg': 'български',
  'hy-am': 'Հայերեն',
  'ur-in': 'اُردُو (بھارت)',
  'ur-pk': 'اُردُو (پاکستان)',
  'ne-np': 'नेपाली भाषा',
  'mr-in': 'मराठी',
  'hi-in': 'Hindi',
  'bn-bd': 'বাংলা (বাংলাদেশ)',
  'bn-in': 'বাংলা (ভারত)',
  'gu-in': 'ગુજરાતી',
  'ta-in': 'தமிழ் (இந்தியா)',
  'ta-lk': 'தமிழ் (இலங்கை)',
  'ta-sg': 'தமிழ் (சிங்கப்பூர்)',
  'ta-my': 'தமிழ் (மலேசியா)',
  'te-in': 'తెలుగు',
  'kn-in': 'ಕನ್ನಡ',
  'ml-in': 'മലയാളം',
  'si-lk': 'සිංහල',
  'th-th': 'ภาษาไทย',
  'lo-la': 'ລາວ',
  'ka-ge': 'ქართული',
  'am-et': 'አማርኛ',
  'km-kh': 'ភាសាខ្មែរ',
  'cmn-hant-tw': 'Chinese',
  'zh-zh': 'Chinese',
  'zh-tw': 'Chinese',
  'zh_tw': 'Chinese',
  'ja-jp': 'Japanese',
  'cmn-hans-cn': 'Chinese',
  'cmn-hans-hk': 'Chinese',
  'yue-hant-hk': 'Cantonese',
  'ko-kr': 'Korean'
};

export const CAPTION_SUMMARY: {[key: string]: string} = {
  'af-za': 'Afrikaans',
  'az-az': 'Azərbaycanca',
  'id-id': 'Bahasa Indonesia',
  'ms-my': 'Bahasa Melayu',
  'jv-id': 'Basa Jawa',
  'su-id': 'Basa Sunda',
  'ca-es': 'Català',
  'da-dk': 'Dansk',
  'de-de': 'German',
  'en-au': 'Summary',
  'en-ca': 'Summary',
  'en-gh': 'Summary',
  'en-in': 'Summary',
  'en-ke': 'Summary',
  'en-nz': 'Summary',
  'en-ng': 'Summary',
  'en-ph': 'Summary',
  'en-za': 'Summary',
  'en-tz': 'Summary',
  'en-gb': 'Summary',
  'en-us': 'Summary',
  'es_es': 'Spanish',
  'es-ar': 'Spanish',
  'es-bo': 'Spanish',
  'es-cl': 'Spanish',
  'es-co': 'Spanish',
  'es-cr': 'Spanish',
  'es-ec': 'Spanish',
  'es-sv': 'Spanish',
  'es-es': 'Spanish',
  'es-us': 'Spanish',
  'es-gt': 'Spanish',
  'es-hn': 'Spanish',
  'es-mx': 'Spanish',
  'es-ni': 'Spanish',
  'es-pa': 'Spanish',
  'es-py': 'Spanish',
  'es-pe': 'Spanish',
  'es-pr': 'Spanish',
  'es-do': 'Spanish',
  'es-uy': 'Spanish',
  'es-ve': 'Spanish',
  'eu-es': 'Spanish',
  'fil-ph': 'Filipino',
  'fr-fr': 'French',
  'gl-es': 'Galego',
  'hr-hr': 'Hrvatski',
  'zu-za': 'IsiZulu',
  'it-it': 'Italiano',
  'it-ch': 'Italiano',
  'sw-ke': 'Kiswahili',
  'sw-tz': 'Kiswahili',
  'lv-lv': 'Latviešu',
  'lt-lt': 'Lietuvių',
  'hu-hu': 'Magyar',
  'nl-nl': 'Nederlands',
  'nb-no': 'Norsk bokmål',
  'pl-pl': 'Polski',
  'pt-br': 'Português',
  'pt-pt': 'Português',
  'ru-ru': 'Pусский',
  'ro-ro': 'Română',
  'sk-sk': 'Slovenčina',
  'sl-si': 'Slovenščina',
  'fi-fi': 'Suomi',
  'sv-se': 'Swedish',
  'vi-vn': 'Tiếng Việt',
  'tr-tr': 'Türkçe',
  'is-is': 'Íslenska',
  'cs-cz': 'Čeština',
  'el-gr': 'Ελληνικά',
  'sr-rs': 'Српски',
  'uk-ua': 'Українська',
  'bg-bg': 'български',
  'hy-am': 'Հայերեն',
  'ur-in': 'اُردُو (بھارت)',
  'ur-pk': 'اُردُو (پاکستان)',
  'ne-np': 'नेपाली भाषा',
  'mr-in': 'मराठी',
  'hi-in': 'Hindi',
  'bn-bd': 'বাংলা (বাংলাদেশ)',
  'bn-in': 'বাংলা (ভারত)',
  'gu-in': 'ગુજરાતી',
  'ta-in': 'தமிழ் (இந்தியா)',
  'ta-lk': 'தமிழ் (இலங்கை)',
  'ta-sg': 'தமிழ் (சிங்கப்பூர்)',
  'ta-my': 'தமிழ் (மலேசியா)',
  'te-in': 'తెలుగు',
  'kn-in': 'ಕನ್ನಡ',
  'ml-in': 'മലയാളം',
  'si-lk': 'සිංහල',
  'th-th': 'ภาษาไทย',
  'lo-la': 'ລາວ',
  'ka-ge': 'ქართული',
  'am-et': 'አማርኛ',
  'km-kh': 'ភាសាខ្មែរ',
  'cmn-hant-tw': '縂結',
  'zh-zh': '总结',
  'zh-tw': '縂結',
  'zh_tw': '縂結',
  'ja-jp': 'Japanese',
  'cmn-hans-cn': '总结',
  'cmn-hans-hk': '縂結',
  'yue-hant-hk': '縂結',
  'ko-kr': 'Korean'
};

export const CAPTION_SUMMARIZING: {[key: string]: string} = {
  'af-za': 'Afrikaans',
  'az-az': 'Azərbaycanca',
  'id-id': 'Bahasa Indonesia',
  'ms-my': 'Bahasa Melayu',
  'jv-id': 'Basa Jawa',
  'su-id': 'Basa Sunda',
  'ca-es': 'Català',
  'da-dk': 'Dansk',
  'de-de': 'German',
  'en-au': 'Summarizing...',
  'en-ca': 'Summarizing...',
  'en-gh': 'Summarizing...',
  'en-in': 'Summarizing...',
  'en-ke': 'Summarizing...',
  'en-nz': 'Summarizing...',
  'en-ng': 'Summarizing...',
  'en-ph': 'Summarizing...',
  'en-za': 'Summarizing...',
  'en-tz': 'Summarizing...',
  'en-gb': 'Summarizing...',
  'en-us': 'Summarizing...',
  'es_es': 'Spanish',
  'es-ar': 'Spanish',
  'es-bo': 'Spanish',
  'es-cl': 'Spanish',
  'es-co': 'Spanish',
  'es-cr': 'Spanish',
  'es-ec': 'Spanish',
  'es-sv': 'Spanish',
  'es-es': 'Spanish',
  'es-us': 'Spanish',
  'es-gt': 'Spanish',
  'es-hn': 'Spanish',
  'es-mx': 'Spanish',
  'es-ni': 'Spanish',
  'es-pa': 'Spanish',
  'es-py': 'Spanish',
  'es-pe': 'Spanish',
  'es-pr': 'Spanish',
  'es-do': 'Spanish',
  'es-uy': 'Spanish',
  'es-ve': 'Spanish',
  'eu-es': 'Spanish',
  'fil-ph': 'Filipino',
  'fr-fr': 'French',
  'gl-es': 'Galego',
  'hr-hr': 'Hrvatski',
  'zu-za': 'IsiZulu',
  'it-it': 'Italiano',
  'it-ch': 'Italiano',
  'sw-ke': 'Kiswahili',
  'sw-tz': 'Kiswahili',
  'lv-lv': 'Latviešu',
  'lt-lt': 'Lietuvių',
  'hu-hu': 'Magyar',
  'nl-nl': 'Nederlands',
  'nb-no': 'Norsk bokmål',
  'pl-pl': 'Polski',
  'pt-br': 'Português',
  'pt-pt': 'Português',
  'ru-ru': 'Pусский',
  'ro-ro': 'Română',
  'sk-sk': 'Slovenčina',
  'sl-si': 'Slovenščina',
  'fi-fi': 'Suomi',
  'sv-se': 'Swedish',
  'vi-vn': 'Tiếng Việt',
  'tr-tr': 'Türkçe',
  'is-is': 'Íslenska',
  'cs-cz': 'Čeština',
  'el-gr': 'Ελληνικά',
  'sr-rs': 'Српски',
  'uk-ua': 'Українська',
  'bg-bg': 'български',
  'hy-am': 'Հայերեն',
  'ur-in': 'اُردُو (بھارت)',
  'ur-pk': 'اُردُو (پاکستان)',
  'ne-np': 'नेपाली भाषा',
  'mr-in': 'मराठी',
  'hi-in': 'Hindi',
  'bn-bd': 'বাংলা (বাংলাদেশ)',
  'bn-in': 'বাংলা (ভারত)',
  'gu-in': 'ગુજરાતી',
  'ta-in': 'தமிழ் (இந்தியா)',
  'ta-lk': 'தமிழ் (இலங்கை)',
  'ta-sg': 'தமிழ் (சிங்கப்பூர்)',
  'ta-my': 'தமிழ் (மலேசியா)',
  'te-in': 'తెలుగు',
  'kn-in': 'ಕನ್ನಡ',
  'ml-in': 'മലയാളം',
  'si-lk': 'සිංහල',
  'th-th': 'ภาษาไทย',
  'lo-la': 'ລາວ',
  'ka-ge': 'ქართული',
  'am-et': 'አማርኛ',
  'km-kh': 'ភាសាខ្មែរ',
  'cmn-hant-tw': '正在縂結...',
  'zh-zh': '正在总结...',
  'zh-tw': '正在縂結...',
  'zh_tw': '正在縂結...',
  'ja-jp': 'Japanese',
  'cmn-hans-cn': '正在总结...',
  'cmn-hans-hk': '正在縂結...',
  'yue-hant-hk': '正在縂結...',
  'ko-kr': 'Korean'
};
